name: nightfalldlp
on:
  push:
    branches:
      - master
  pull_request:
permissions:
  contents: read
  checks: write
jobs:
  nightfalldlp:
    name: nightfalldlp
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo Action
        uses: actions/checkout@v2
      - name: List files in the repository
          run: |
            ls ${{github.workspace}}
          -run: echo "This job's status is ${{job.status}}."
      - name: nightfallDLP action step
        uses: nightfallai/nightfall_dlp_action@v2.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NIGHTFALL_API_KEY: ${{ secrets.NIGHTFALL_API_KEY }}
          EVENT_BEFORE: ${{ github.event.before }}
